### ISSUE TITLE
Instructions for setting up Quillpad server on windows

### ISSUE THREAD

**Issue by pkapare** [CognirelTech/Quillpad-Server#2] opened 2016-12-09 23:57 UTC
Hi,
Could you please help me with instructions for setting up Quillpad  server on Windows?
Thanks

**Comment by cognirel** [comment] 2016-12-22 04:24
Hi,
Those instructions given in the documentation are for linux and mac.

For installing on windows, change the line in the instructions in the installation section from
`cp QuillCCart.so ../../`
to
`cp QuillCCart.pyd ../../`

and you should be good to go.

**Comment by sharathpuranik** [comment] 2016-12-27 06:46
Duplicate of issue #1

**Closed by sharathpuranik** 2016-12-27 06:46 UTC
